In [3]:
import pandas as pd

In [7]:
l1=[1,2,3,4,5,6,7]
s1=pd.Series(l1)
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [9]:
person1={
    "name":["swapna",'tunia'],
    "age":[21,22],
    "job":["sd",'sde']
}
df1=pd.DataFrame(person1)
df1

     name  age  job
0  swapna   21   sd
1   tunia   22  sde

# from dictinary

In [11]:
df2=pd.DataFrame({
    "name":["swapna",'tunia'],
    "age":[21,22],
    "job":["sd",'sde']
})
df2

     name  age  job
0  swapna   21   sd
1   tunia   22  sde

# from list

In [15]:
df3=pd.DataFrame([[1,2,3,4],[5,6,7,8]])
df3

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [28]:
df4=pd.DataFrame([[1,2,3,4],[5,6,7,8]], columns=['A','B','C','D'])
df4

   A  B  C  D
0  1  2  3  4
1  5  6  7  8

## from numpy array

In [29]:
import numpy as np

In [31]:
arra1=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [33]:
df4=pd.DataFrame(arra1, columns=['A','B','C','D','E'])
df4

   A  B  C  D   E
0  1  2  3  4   5
1  6  7  8  9  10

# from excel/csv file

In [35]:
df5=pd.read_csv('day.csv')
df5

    Numeric  Numeric-2 Numeric-Suffix
0         1          1            1st
1         2          2            2nd
2         3          3            3rd
3         4          4            4th
4         5          5            5th
5         6          6            6th
6         7          7            7th
7         8          8            8th
8         9          9            9th
9        10         10           10th
10       11         11           11th
11       12         12           12th
12       13         13           13th
13       14         14           14th
14       15         15           15th
15       16         16           16th
16       17         17           17th
17       18         18           18th
18       19         19           19th
19       20         20           20th
20       21         21           21st
21       22         22           22nd
22       23         23           23rd
23       24         24           24th
24       25         25           25th
25       26         26           26th
26       27         27           27th
27       28         28           28th
28       29         29           29th
29       30         30           30th
30       31         31           31st

# from List of tuples

In [36]:
data=[(1,"swapna",23),
      (2,"tunia",21),
      (3,"smith",22)]
df8=pd.DataFrame(data,columns=['sl-no','name','age'])
df8

   sl-no    name  age
0      1  swapna   23
1      2   tunia   21
2      3   smith   22

# from list of dictionary

In [38]:
data2=[{"name":"swapna",'age':23,'job':'sde'},
       {'name':'tunia',"age":"21",'job':'sd'},
       {'name':'paro','age':'22','job':'sd'}]
df9=pd.DataFrame(data2)
df9

     name age  job
0  swapna  23  sde
1   tunia  21   sd
2    paro  22   sd